project:
  type: hugo
  output-dir: hugo
  post-render: /bin/sh -c "cd hugo &&  hugo --buildDrafts --cleanDestinationDir"
  # post-render: /bin/sh -c "cd hugo &&  hugo --cleanDestinationDir"
format:
  hugo-md:
    code-fold: true
execute:
  echo: false
  warning: false
  message: false
  cache: false
  freeze: auto
engine: knitr
knitr:
  opts_chunk:
    out.width: "100%"
    # dev: ragg_png
    dev: svglite
    dev.args: { scaling: 1, bg: "transparent" }
editor: source
editor_options:
  chunk_output_type: console
