---
title: "Einsatz neuer Daten in Kommunikationszusammenhängen auf Unternehmensebene"
figtitle: "💾"
date: "2024-11-25T14:25:49+01:00"
draft: false
tags: 
    - "foo"
    - "bar"
format: "hugo-md"
output-file: "_index.md"
layout: "home"
toc_show: false
---

<!-- Kommunikationsdaten umfassen Informationen, die bei der Interaktion zwischen Personen oder zwischen Personen und Geräten anfallen. Dazu gehören nicht nur die unmittelbaren Inhalte der Kommunikation, sondern auch verschiedene Metadaten wie Sender- und Empfängerinformationen, Zeitstempel, Betreffzeilen und mehr. Diese Daten können aus verschiedenen Quellen stammen, wie E-Mails, Textnachrichten, Chatprotokollen, sozialen Medien, Kundenanfragen und Kundenbefragungen. Für hessische Unternehmen können diese Kommunikationsdaten eine wertvolle Informationsquelle darstellen, deren Analyse wirtschaftlichen Mehrwert generieren kann.. -->

<!-- {{{< div id="chart" >}}} {{{< /div >}}}
<script src="/assets/js/wordcloud.js"></script> -->

{{{< div class="container-fluid pb-2" style="background: #e9ebe5 !important;" >}}}
  {{{< div class="container-xxl py-4 grid nd-article" >}}}
    {{{< div class="g-col-12" >}}} {{{< span class="h1" >}}} Einsatz neuer Daten in Kommunikationszusammenhängen auf Unternehmensebene {{{< /span >}}} <br> {{{< span class="lead" >}}} ***Förderprogramm Distr@l Digitalisierung*** {{{< /span >}}} {{{< /div >}}}
    {{{< div class="g-col-12 g-col-md-8 order-md-1" >}}}
      {{{< p >}}} **Kommunikationsdaten** entstehen durch E-Mails, Berichte, soziale Medien oder Kundenanfragen und enthalten wertvolle Informationen für Unternehmen. Doch oft bleiben sie ungenutzt, da sie unstrukturiert sind und ihre Analyse aufwendig erscheint. Computergestützte Verfahren ermöglichen jedoch die automatisierte Auswertung großer Datenmengen in kurzer Zeit – für bessere Einblicke und fundierte Entscheidungen. {{{< /p >}}} {{{< p class="pb-4" >}}} Hier setzt das **EnDiKaU-Projekt** der Justus-Liebig-Universität Gießen im Rahmen des **Förderprogramms Distr@l Digitalisierung** an. Ziel des Projekts ist es, **kleinen und mittelständischen Unternehmen (KMU)** Methoden der **computergestützten Textanalyse** zugänglich zu machen und **praxisnahe Anwendungsmöglichkeiten** aufzuzeigen, um eine fundierte Grundlage für den Einsatz dieser Methoden im eigenen Unternehmen zu schaffen. {{{< /p >}}} 
      <!-- {{{< div class="text-white text-bg-primary rounded p-3" >}}} -->
      <!--   {{{< p class="p-0" >}}} Unsere Website bietet Ihnen eine Übersicht der vielfältigen Werkzeuge, mit denen Kommunikationsdaten analysiert und genutzt werden können. Von den Grundlagen dieser Daten über Methoden, diese zu strukturieren und auszuwerten, bis hin zu praktischen Anwendungen – entdecken Sie, wie diese Methoden dazu beitragen können, wertvolle Erkenntnisse aus Kommunikationsdaten zu gewinnen. {{{< /p >}}} -->
      <!-- {{{< /div >}}} -->
    {{{< /div >}}}
    {{{< div class="g-col-12 g-col-md-4 order-md-2" >}}}
      {{{< div class="d-flex justify-content-center" style="max-width: 500px;" >}}}

```{r, dev="svglite", dev.args=list(bg="transparent")}
#| out-width: "100%"
library(ggraph)
library(tidygraph)

highschool |> 
  as_tbl_graph() |> 
  ggraph() +
  geom_edge_link(aes(colour = factor(year)), linewidth=1.5) +
  geom_node_point(size=4) +
  scale_edge_color_manual(values=rcartocolor::carto_pal(2, "Temps")) +
  coord_equal() +
  theme_void() +
  theme(legend.position="none")
```

      {{{< /div >}}}
    {{{< /div >}}}
  {{{< /div >}}}
{{{< /div >}}}

{{{< div class="container-fluid" style="background: #fefffc !important;" >}}} {{{< div class="container-xxl py-4 nd-article" >}}} 

## Methoden

<!-- `{r} stringi::stri_rand_lipsum(1)` -->
<!-- Datenwissenschaftliche Methoden ermöglichen es, große Mengen an Textdaten zu analysieren, zu strukturieren und wertvolle Erkenntnisse daraus zu gewinnen. Verschiedene Techniken helfen dabei, Muster zu erkennen, Informationen zu kategorisieren und komplexe Zusammenhänge sichtbar zu machen. -->

{{{< div class="grid py-2" >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4 nd-article" >}}} 
        {{{< p class="nd-article" >}}} Von Stimmungsanalysen bis hin zu Themenerkennung – moderne Analysemethoden ermöglichen es, versteckte Botschaften in großen Textmengen aufzudecken. Wählen Sie eine Methode, um zu erfahren, wie sie funktioniert und welche Erkenntnisse sie liefern kann. {{{< /p >}}}
    {{{< /div >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4" >}}} 
        {{{< bs_card card_img_src="/assets/img/sentiment_cover.svg" card_img_bg="#9c9c9c" card_title="Sentimentanalyse" card_text="Sentimentanalyse ist ein Verfahren der Data Science, das darauf abzielt, Meinungen, Emotionen und Einstellungen in Textdaten automatisch zu identifizieren und zu klassifizieren." card_href="/methods/sentiment" >}}}
    {{{< /div >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4" >}}} 
        {{{< bs_card card_img_src="/assets/img/topic_cover.svg" card_img_bg="#9c9c9c" card_title="Themenmodellierung" card_text="Die Themenmodellierung extrahiert automatisiert Hauptthemen aus Texten. Dies ermöglicht die Extraktion semantisch verwandter Begriffe, sowie die Gruppierung thematisch ähnlicher Dokumente." card_href="/methods/topic" >}}}
    {{{< /div >}}} 
{{{< /div >}}} 

{{{< /div >}}} {{{< /div >}}} 



{{{< div class="container-fluid" >}}} {{{< div class="container-xxl py-4 nd-article" >}}}

## Fallstudien

<!-- `{r} stringi::stri_rand_lipsum(1)` -->

{{{< div class="grid py-2" >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4" >}}} 
        {{{< p class="nd-article" >}}} Unsere Fallstudien veranschaulichen, wie Technologien der Textanalyse auf reale Daten angewendet werden. Entdecken Sie konkrete Beispiele für den Einsatz von Sentimentanalyse, Themenmodellierung und weiteren Methoden. {{{< /p >}}}
    {{{< /div >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4" >}}} 
        {{{< bs_card_emoji emoji_code="2b50" emoji_bg="#837591" card_title="Kundenrezensionen" card_text="In dieser Case Study zeigen wir, wie unstrukturierte Kundenrezensionen mithilfe von Textanalyse systematisch ausgewertet werden können, um differenzierte Einblicke in die Nutzung technischer Produkte zu gewinnen und gezielt Verbesserungspotenziale zu identifizieren." card_href="/case_studies/customer_reviews" >}}}
    {{{< /div >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4" >}}} 
        {{{< bs_card_emoji emoji_code="1f4e9" emoji_bg="#837591" card_title="Analyse von Support-Tickets" card_text="Dieses Fallbeispiel zeigt, wie sich Support-Anfragen allein anhand der Texte automatisiert nach Dringlichkeit klassifizieren lassen. Durch den gezielten Einsatz von Textanalyse und Machine Learning werden besonders kritische Anliegen frühzeitig erkannt, um den Kundenservice effizienter zu gestalten." card_href="/case_studies/support_tickets" >}}}
    {{{< /div >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4" >}}} 
        {{{< bs_card_emoji emoji_code="1f4f0" emoji_bg="#9c9c9c" card_title="Fallstudie I" card_text="Lorem Ipsum" card_href="/case_studies/case_study-1" >}}}
    {{{< /div >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4" >}}} 
        {{{< bs_card_emoji emoji_code="1f4f0" emoji_bg="#9c9c9c" card_title="Fallstudie II" card_text="Lorem Ipsum" card_href="/case_studies/case_study-2" >}}}
    {{{< /div >}}} 
    {{{< div class="g-col-12 g-col-md-6 g-col-xl-4" >}}} 
        {{{< bs_card_emoji emoji_code="1f4f0" emoji_bg="#9c9c9c" card_title="Fallstudie III" card_text="Lorem Ipsum" card_href="/case_studies/case_study-3" >}}}
    {{{< /div >}}} 
{{{< /div >}}}

{{{< /div >}}} {{{< /div >}}}

<!-- {{{< div class="container-fluid" style="background: #fefffc !important;" >}}} {{{< div class="container-xxl py-4 nd-article" >}}}  -->

<!-- ## Palette -->

<!-- ```{r} -->
<!-- library(ggplot2) -->

<!-- palette <- tibble::tribble( -->
<!--   ~color, ~palette, -->
<!--   "#2e2933", "base", -->
<!--   "#837591", "base", -->
<!--   "#e9ebe5", "base", -->
<!--   "#cf597e", "diverging", -->
<!--   "#e88471", "diverging", -->
<!--   "#eeb479", "diverging", -->
<!--   "#e9e29c", "diverging", -->
<!--   "#9ccb86", "diverging", -->
<!--   "#39b185", "diverging", -->
<!--   "#009392", "diverging", -->
<!--   "#f7feae", "sequential", -->
<!--   "#b7e6a5", "sequential", -->
<!--   "#7ccba2", "sequential", -->
<!--   "#46aea0", "sequential", -->
<!--   "#089099", "sequential", -->
<!--   "#00718b", "sequential", -->
<!--   "#045275", "sequential", -->
<!-- ) -->

<!-- palette |>  -->
<!--   dplyr::mutate( -->
<!--     color_palette_rank = dplyr::row_number(), .by=palette -->
<!--   ) |> -->
<!--   ggplot(aes(x=color_palette_rank, y=forcats::fct_rev(palette), fill=color)) + -->
<!--   geom_tile(width=1) + -->
<!--   geom_text(aes(label=color), color="black", nudge_x=0.1, nudge_y=0.1) + -->
<!--   geom_text(aes(label=color), color="white", nudge_x=-0.1, nudge_y=-0.1) + -->
<!--   scale_fill_identity() + -->
<!--   coord_equal() + -->
<!--   theme_minimal() + -->
<!--   theme( -->
<!--     axis.title=element_blank(), -->
<!--     axis.text.x=element_blank(), -->
<!--     axis.ticks.x=element_blank(), -->
<!--     panel.grid=element_blank() -->
<!--   ) -->
<!-- ``` -->

<!-- ## Emojis -->

<!-- 📧📨📄👥👤🗣️🌐📱📰📣 -->


<!-- {{{< /div >}}} {{{< /div >}}} -->

